Spring:
  datasource:
    username: pet_store
    password: pet_store
    url: jdbc:mysql://localhost:3306/pet_store
    
  jpa:
    hibernate:
      #the "create" option will wipe out pre-existing data and recreate the tables
      #the "update" will keep existing data and update the tables with new information
      ddl-auto: update
    show-sql: true